package datasource

import (
	"reflect"

	apiextensionsv1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

const (
	schemaName   = "datasource"
	groupName    = "datasource.grafana.core.group"
	groupVersion = "v1alpha1"
)

var (
	openapiSchema = apiextensionsv1beta1.JSONSchemaProps{}
)

// Model
type Model struct {
	// Omitting these two at least for now, because sequential IDs == :(
	// Id                int64                  `json:"id"`
	// OrgId int64 `json:"orgId"` // May change, but to make store work

	//UID               string `json:"uid"` // May change, but to make store work
	//Name              string `json:"name"`
	Type              string `json:"type"`
	TypeLogoUrl       string `json:"typeLogoUrl"`
	Access            string `json:"access"` // enum: *"proxy" | "direct"
	Url               string `json:"url"`
	Password          string `json:"password"`
	User              string `json:"user"`
	Database          string `json:"database"`
	BasicAuth         bool   `json:"basicAuth"`
	BasicAuthUser     string `json:"basicAuthUser"`
	BasicAuthPassword string `json:"basicAuthPassword"`
	WithCredentials   bool   `json:"withCredentials,omitempty"`
	IsDefault         bool   `json:"isDefault"`
	// JsonData          *simplejson.Json       `json:"jsonData,omitempty"`
	JsonData         map[string]interface{} `json:"jsonData,omitempty"`
	SecureJsonFields map[string]bool        `json:"secureJsonFields,omitempty"`
	Version          int                    `json:"version"`
	ReadOnly         bool                   `json:"readOnly"`
	// AccessControl     accesscontrol.Metadata `json:"accessControl,omitempty"`
	AccessControl map[string]bool `json:"accessControl,omitempty"`
}

// TODO this should be generated by thema
type ModelStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
}

// TODO this should be generated by thema
type CR struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   Model       `json:"spec,omitempty"`
	Status ModelStatus `json:"status,omitempty"`
}

func (in *CR) DeepCopyObject() runtime.Object {
	val := reflect.ValueOf(in).Elem()

	cpy := reflect.New(val.Type())
	cpy.Elem().Set(val)

	// This might panic, so consider adding `recover` and stuff.
	return cpy.Interface().(runtime.Object)
}

// TODO this should be generated by thema
type CRList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CR `json:"items"`
}

func (in *CRList) DeepCopyObject() runtime.Object {
	panic("not implemented")
}
