{
 "title": "Tableau de bord principal",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "observable",
    "query": "SELECT distinct(observable_path) as observable\nFROM input_view\nWHERE $__timeFilter(date_time)\nORDER BY observable"
   },
   { "name": "interval", "label": "Laps de temps", "query": "1h,6h,12h,1d,7d,14d,1M,6M,1y" },
   {
    "name": "indicators",
    "label": "Indicateurs",
    "query": "SELECT DISTINCT(indicator_path) as indicator\nFROM input_view\nWHERE $__timeFilter(date_time) AND observable_path = \"$observable\"\nORDER BY indicator"
   }
  ]
 },
 "panels": [
  {
   "title": "Évolution des indicateurs dans le temps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,$interval),\n  indicator_path AS metric,\n  sum(value) AS \"value\"\nFROM input_view\nWHERE\n  $__timeFilter(date_time) AND\n  indicator_path IN ($indicators) AND\n  observable_path = \"$observable\"\nGROUP BY 1,2\nORDER BY $__timeGroup(date_time,$interval)"
    }
   ]
  },
  {
   "title": "Répartition entre les indicateurs",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,100y,NULL),\n  indicator_path AS metric,\n  sum(value) AS \"value\"\nFROM input_view\nWHERE\n  $__timeFilter(date_time) AND\n  indicator_path IN ($indicators) AND\n  observable_path = \"$observable\"\nGROUP BY 1,2\nORDER BY $__timeGroup(date_time,100y,NULL)"
    }
   ]
  },
  {
   "title": "Distribution du nombre d'épisodes par tranche horaire",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour(date_time) * 3600 + UNIX_TIMESTAMP(current_date) as time,\n  concat(hour(date_time), 'h') AS hour\nFROM input_view\nWHERE\n  $__timeFilter(date_time) and indicator_path in ($indicators)\nGROUP BY 1,2\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  hour(date_time) * 3600 + UNIX_TIMESTAMP(current_date) as time,\n  indicator_path,\n  sum(value) AS ''\nFROM input_view\nWHERE\n  $__timeFilter(date_time) AND\n  indicator_path in ($indicators) AND\n  observable_path = \"$observable\"\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}